title: Rajakoti Dasari
description: Data Engineer | AI/ML Enthusiast | NLP | Computer Vision
baseurl: "" # Keep this blank for user/organization GitHub Pages
url: "https://rajadasari007.github.io" # Change if you use a custom domain
theme: minima

# Optional
author:
  name: "Rajakoti Dasari"
  email: "your-email@example.com"

plugins:
  - jekyll-seo-tag
